# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 23:15
from __future__ import unicode_literals

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('first_seen', models.DateTimeField(default=common.models.utcnow)),
                ('created', models.DateTimeField(default=common.models.utcnow)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('client_id', models.UUIDField()),
                ('rsvp', models.NullBooleanField()),
                ('details', models.TextField(default='')),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
