# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('in-progress', 'in-progress'), ('complete', 'complete')], default='in-progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
